CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'aluno')),
    CONSTRAINT uq_usuario_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS aluno (
    aluno_id BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
    matricula VARCHAR(12) NOT NULL,
    CONSTRAINT uq_aluno_matricula UNIQUE (matricula)
);

CREATE TABLE IF NOT EXISTS administracao (
    id BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
    siap BIGINT NOT NULL,
    CONSTRAINT uq_administracao_siap UNIQUE (siap)
);

CREATE TABLE IF NOT EXISTS categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    CONSTRAINT uq_categoria_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS local (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_local VARCHAR(150) NOT NULL,
    descricao TEXT,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_local_nome UNIQUE (nome_local)
);

CREATE TABLE IF NOT EXISTS item_perdido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    data_encontrado DATE NOT NULL DEFAULT CURRENT_DATE,
    foto_url VARCHAR(2048),
    local_id BIGINT NOT NULL REFERENCES local(id),
    categoria_id BIGINT NOT NULL REFERENCES categoria(id),
    registrado_por BIGINT NOT NULL REFERENCES usuario(id),
    status VARCHAR(30) NOT NULL DEFAULT 'disponível'
);

CREATE TABLE IF NOT EXISTS reivindicacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_reivindicacao VARCHAR(30) NOT NULL DEFAULT 'pendente',
    data_solicitacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    item_id BIGINT NOT NULL REFERENCES item_perdido(id),
    aluno_id BIGINT NOT NULL REFERENCES aluno(aluno_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_reivindicacao_ativa
    ON reivindicacao (item_id, aluno_id)
    WHERE status_reivindicacao = 'pendente';

INSERT INTO categoria (nome) VALUES
    ('Chaves'),
    ('Garrafas'),
    ('Documentos'),
    ('Eletronicos'),
    ('Bolsas'),
    ('Livros'),
    ('Outros')
ON CONFLICT (nome) DO NOTHING;

INSERT INTO local (nome_local, descricao) VALUES
    ('Bloco 1', 'Salas e corredores do Bloco 1'),
    ('Bloco 2', 'Salas e corredores do Bloco 2'),
    ('Bloco 3', 'Salas e corredores do Bloco 3'),
    ('Bloco 4', 'Salas e corredores do Bloco 4'),
    ('Bloco 5', 'Salas e corredores do Bloco 5'),
    ('Biblioteca', 'Biblioteca do campus'),
    ('Restaurante Universitario', 'Area do restaurante universitario'),
    ('Recepcao', 'Recepcao e portaria principal'),
    ('Estacionamento', 'Area de estacionamento do campus'),
    ('Laboratorio', 'Laboratorios do campus'),
    ('Area de Convivencia', 'Area de convivência do campus')
ON CONFLICT (nome_local) DO NOTHING;
