-- =============================================================
--  Achou! UFC Quixadá — init.sql
--  Ordem: tabelas → índices → seeds obrigatórios → seeds de teste
-- =============================================================

-- ── Tabelas ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS usuario (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(150) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    senha      VARCHAR(255) NOT NULL,
    criado_em  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    role       VARCHAR(20)  NOT NULL CHECK (role IN ('admin', 'aluno')),
    CONSTRAINT uq_usuario_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS aluno (
    aluno_id  BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
    matricula VARCHAR(12) NOT NULL,
    CONSTRAINT uq_aluno_matricula UNIQUE (matricula)
);

CREATE TABLE IF NOT EXISTS administracao (
    id   BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
    siap BIGINT NOT NULL,
    CONSTRAINT uq_administracao_siap UNIQUE (siap)
);

CREATE TABLE IF NOT EXISTS categoria (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    CONSTRAINT uq_categoria_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS local (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_local VARCHAR(150) NOT NULL,
    descricao  TEXT,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_local_nome UNIQUE (nome_local)
);

CREATE TABLE IF NOT EXISTS item_perdido (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo          VARCHAR(255) NOT NULL,
    descricao       TEXT,
    data_encontrado DATE         NOT NULL DEFAULT CURRENT_DATE,
    foto_url        VARCHAR(2048),
    local_id        BIGINT       NOT NULL REFERENCES local(id),
    categoria_id    BIGINT       NOT NULL REFERENCES categoria(id),
    registrado_por  BIGINT       NOT NULL REFERENCES usuario(id),
    status          VARCHAR(30)  NOT NULL DEFAULT 'disponivel'
);

CREATE TABLE IF NOT EXISTS reivindicacao (
    id                   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_reivindicacao VARCHAR(30) NOT NULL DEFAULT 'pendente',
    data_solicitacao     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    item_id              BIGINT      NOT NULL REFERENCES item_perdido(id),
    aluno_id             BIGINT      NOT NULL REFERENCES aluno(aluno_id)
);

-- Impede dois pedidos pendentes do mesmo aluno para o mesmo item
CREATE UNIQUE INDEX IF NOT EXISTS uq_reivindicacao_ativa
    ON reivindicacao (item_id, aluno_id)
    WHERE status_reivindicacao = 'pendente';


-- =============================================================
--  SEEDS OBRIGATÓRIOS — não remova, o sistema depende destes
-- =============================================================

INSERT INTO categoria (nome) VALUES
    ('Chaves'),
    ('Garrafas'),
    ('Documentos'),
    ('Eletronicos'),
    ('Bolsas'),
    ('Livros'),
    ('Outros')
ON CONFLICT (nome) DO NOTHING;

INSERT INTO local (nome_local, descricao) VALUES
    ('Bloco 1',                  'Salas e corredores do Bloco 1'),
    ('Bloco 2',                  'Salas e corredores do Bloco 2'),
    ('Biblioteca',               'Biblioteca do campus'),
    ('Restaurante Universitario','Area do restaurante universitario'),
    ('Quadra',                   'Area esportiva'),
    ('Recepcao',                 'Recepcao e portaria principal')
ON CONFLICT (nome_local) DO NOTHING;


CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO usuario (id, nome, email, senha, role) VALUES
    (1, 'Administrador Local',  'admin@ufc.br',       crypt('Admin@123', gen_salt('bf', 12)), 'admin'),
    (5, 'Administrador Local',  'admin2@ufc.br',      crypt('Admin@123', gen_salt('bf', 12)), 'admin'),
    (2, 'Aluno Teste',          'aluno@alu.ufc.br',   crypt('Aluno@123', gen_salt('bf', 12)), 'aluno'),
    (3, 'Maria Silva',          'maria@alu.ufc.br',   crypt('Aluno@123', gen_salt('bf', 12)), 'aluno'),
    (4, 'Joao Ferreira',        'joao@alu.ufc.br',    crypt('Aluno@123', gen_salt('bf', 12)), 'aluno')
ON CONFLICT (email) DO NOTHING;

INSERT INTO administracao (id, siap) VALUES
    (1, 123456)
ON CONFLICT (siap) DO NOTHING;

INSERT INTO aluno (aluno_id, matricula) VALUES
    (2, '399876543'),
    (3, '399812001'),
    (4, '399800042')
ON CONFLICT (matricula) DO NOTHING;

-- Avança as sequences para não colidir com os IDs fixos acima
SELECT setval(pg_get_serial_sequence('usuario',  'id'), GREATEST((SELECT MAX(id) FROM usuario),  10), true);
SELECT setval(pg_get_serial_sequence('categoria','id'), GREATEST((SELECT MAX(id) FROM categoria), 10), true);
SELECT setval(pg_get_serial_sequence('local',    'id'), GREATEST((SELECT MAX(id) FROM local),     10), true);


-- =============================================================
--  ITENS DE TESTE — variedade de status, categorias e locais
--  registrado_por = 1 (admin)
--  IDs de categoria: 1=Chaves 2=Garrafas 3=Documentos
--                    4=Eletronicos 5=Bolsas 6=Livros 7=Outros
--  IDs de local:     1=Bloco1 2=Bloco2 3=Biblioteca
--                    4=Restaurante 5=Quadra 6=Recepcao
-- =============================================================

INSERT INTO item_perdido (titulo, descricao, data_encontrado, foto_url, local_id, categoria_id, registrado_por, status) VALUES

    -- Chaves
    (
        'Chave com chaveiro de urso',
        'Chave simples com chaveiro de pelúcia de urso marrom. Encontrada no corredor do Bloco 1 perto da sala 102.',
        CURRENT_DATE - INTERVAL '1 day',
        NULL,
        1, 1, 1, 'disponivel'
    ),
    (
        'Molho de chaves — 3 chaves',
        'Três chaves num argolão de metal. Uma delas tem fita adesiva verde na ponta. Encontrado embaixo de uma cadeira.',
        CURRENT_DATE - INTERVAL '5 days',
        NULL,
        2, 1, 1, 'disponivel'
    ),

    -- Garrafas
    (
        'Garrafa Stanley cinza 1L',
        'Garrafa térmica Stanley na cor cinza chumbo, capacidade 1 litro. Tem um adesivo de banda de rock na lateral.',
        CURRENT_DATE - INTERVAL '2 days',
        NULL,
        3, 2, 1, 'disponivel'
    ),
    (
        'Garrafa squeeze rosa',
        'Squeeze plástico rosinha com marca d''água no interior. Tampinha branca. Encontrada no Restaurante Universitário.',
        CURRENT_DATE - INTERVAL '8 days',
        NULL,
        4, 2, 1, 'em_analise'
    ),

    -- Documentos
    (
        'Carteira de identidade — João P.',
        'RG em nome de João Paulo, emitido pela SSP-CE. Encontrado na quadra após as aulas de educação física.',
        CURRENT_DATE - INTERVAL '3 days',
        NULL,
        5, 3, 1, 'disponivel'
    ),
    (
        'Cartão universitário UFC',
        'Cartão de identificação estudantil da UFC. Nome ilegível — cartão desgastado. Foto visível no cartão.',
        CURRENT_DATE - INTERVAL '10 days',
        NULL,
        6, 3, 1, 'devolvido'
    ),
    (
        'CNH vencida com outros documentos',
        'Carteira com CNH vencida, um cartão de crédito bloqueado e foto de família. Sem dinheiro. Achado na Biblioteca.',
        CURRENT_DATE - INTERVAL '4 days',
        NULL,
        3, 3, 1, 'disponivel'
    ),

    -- Eletrônicos
    (
        'Fone de ouvido JBL preto',
        'Fone over-ear JBL preto, sem fio, com case de carregamento. Case tem um adesivo de dinossauro verde.',
        CURRENT_DATE - INTERVAL '1 day',
        NULL,
        1, 4, 1, 'disponivel'
    ),
    (
        'Carregador USB-C branco 65W',
        'Carregador de notebook USB-C de 65W, marca genérica, cor branca. Cabo ainda enrolado com elástico.',
        CURRENT_DATE - INTERVAL '6 days',
        NULL,
        2, 4, 1, 'disponivel'
    ),
    (
        'Mouse sem fio Logitech',
        'Mouse sem fio Logitech M190 na cor azul. Sem pilha. Encontrado em cima de uma mesa na Biblioteca.',
        CURRENT_DATE - INTERVAL '12 days',
        NULL,
        3, 4, 1, 'arquivado'
    ),
    (
        'Fio de carregador iPhone entrelaçado',
        'Cabo Lightning branco enrolado. Conector um pouco dobrado mas funciona. Achado na Recepção.',
        CURRENT_DATE - INTERVAL '2 days',
        NULL,
        6, 4, 1, 'disponivel'
    ),

    -- Bolsas
    (
        'Mochila preta com patch de guitarra',
        'Mochila escolar preta com patch bordado de guitarra elétrica na frente. Contém caderno e estojo vazios.',
        CURRENT_DATE - INTERVAL '3 days',
        NULL,
        2, 5, 1, 'disponivel'
    ),
    (
        'Necessaire transparente',
        'Necessaire de plástico transparente com zíper azul. Contém protetor solar, batom e fone de ouvido com fio.',
        CURRENT_DATE - INTERVAL '7 days',
        NULL,
        4, 5, 1, 'em_analise'
    ),

    -- Livros
    (
        'Livro "Clean Code" — Robert C. Martin',
        'Livro técnico de programação em bom estado. Nome "Lucas" escrito a caneta na primeira página.',
        CURRENT_DATE - INTERVAL '9 days',
        NULL,
        3, 6, 1, 'disponivel'
    ),
    (
        'Apostila de Cálculo II — folhas soltas',
        'Conjunto de folhas A4 impressas frente e verso, preso com clipe. Cobre até integral dupla.',
        CURRENT_DATE - INTERVAL '4 days',
        NULL,
        1, 6, 1, 'disponivel'
    ),

    -- Outros
    (
        'Guarda-chuva dobrável azul marinho',
        'Guarda-chuva compacto dobrável, cor azul marinho com detalhes cinza. Alça de borracha preta.',
        CURRENT_DATE - INTERVAL '1 day',
        NULL,
        6, 7, 1, 'disponivel'
    ),
    (
        'Óculos de grau — armação vinho',
        'Óculos de grau com lente de aumento, armação vinho escuro. Sem estojo. Grau não identificado.',
        CURRENT_DATE - INTERVAL '5 days',
        NULL,
        1, 7, 1, 'disponivel'
    ),
    (
        'Copo térmico do Corinthians',
        'Copo térmico com estampa do Corinthians, cor preta e branca, capacidade 500ml. Tampa de rosca.',
        CURRENT_DATE - INTERVAL '15 days',
        NULL,
        4, 7, 1, 'devolvido'
    );

-- Avança a sequence de item_perdido para não colidir
SELECT setval(pg_get_serial_sequence('item_perdido', 'id'), GREATEST((SELECT MAX(id) FROM item_perdido), 20), true);


-- =============================================================
--  REIVINDICAÇÕES DE TESTE
--  Cobre os 3 status: pendente, aprovado, recusado
-- =============================================================

INSERT INTO reivindicacao (status_reivindicacao, data_solicitacao, item_id, aluno_id) VALUES
    -- Aluno 2 reivindica a garrafa squeeze (item 4, status em_analise) → pendente
    ('pendente',  NOW() - INTERVAL '1 day',   4,  2),
    -- Aluno 3 reivindica a necessaire (item 13, status em_analise) → pendente
    ('pendente',  NOW() - INTERVAL '3 hours', 13, 3),
    -- Aluno 2 já tinha reivindicado o cartão universitário (item 6) → aprovado → item devolvido
    ('aprovado',  NOW() - INTERVAL '9 days',  6,  2),
    -- Aluno 4 tentou reivindicar o mouse Logitech (item 10, arquivado) → recusado
    ('recusado',  NOW() - INTERVAL '11 days', 10, 4),
    -- Aluno 3 reivindica o copo do Corinthians (item 18, devolvido) → aprovado
    ('aprovado',  NOW() - INTERVAL '14 days', 18, 3);

SELECT setval(pg_get_serial_sequence('reivindicacao', 'id'), GREATEST((SELECT MAX(id) FROM reivindicacao), 10), true);