require('dotenv').config();
const { Client } = require('pg');

async function executarCarga() {
    const client = new Client({
        user: process.env.DB_USER,
        host: process.env.DB_HOST,
        database: process.env.DB_NAME,
        password: process.env.DB_PASS,
        port: process.env.DB_PORT,
    });

    try {
        await client.connect();
        console.log("Conectado ao banco de dados.");

        // Inicia a transação
        await client.query('BEGIN');
        console.log("Transação iniciada.");

        // 0. Limpeza do banco (Garante que o script possa rodar múltiplas vezes sem erro de UNIQUE)
        console.log("Limpando base de dados (TRUNCATE CASCADE)...");
        await client.query('TRUNCATE TABLE usuario, categoria, local CASCADE');

        // 1. Criar Tabelas
        console.log("Criando tabelas...");
        const ddlQuery = `
            CREATE TABLE IF NOT EXISTS usuario (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome VARCHAR(150) NOT NULL,
                email VARCHAR(255) NOT NULL,
                senha VARCHAR(255) NOT NULL,
                criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'aluno')),
                CONSTRAINT uq_usuario_email UNIQUE (email)
            );

            CREATE TABLE IF NOT EXISTS aluno (
                aluno_id BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
                matricula VARCHAR(12) NOT NULL,
                CONSTRAINT uq_aluno_matricula UNIQUE (matricula)
            );

            CREATE TABLE IF NOT EXISTS administracao (
                id BIGINT PRIMARY KEY REFERENCES usuario(id) ON DELETE CASCADE,
                siap BIGINT NOT NULL,
                CONSTRAINT uq_administracao_siap UNIQUE (siap)
            );

            CREATE TABLE IF NOT EXISTS categoria (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome VARCHAR(120) NOT NULL,
                CONSTRAINT uq_categoria_nome UNIQUE (nome)
            );

            CREATE TABLE IF NOT EXISTS local (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome_local VARCHAR(150) NOT NULL,
                descricao TEXT,
                deleted_at TIMESTAMPTZ,
                CONSTRAINT uq_local_nome UNIQUE (nome_local)
            );

            CREATE TABLE IF NOT EXISTS item_perdido (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                titulo VARCHAR(255) NOT NULL,
                descricao TEXT,
                data_encontrado DATE NOT NULL DEFAULT CURRENT_DATE,
                foto_url VARCHAR(2048),
                local_id BIGINT NOT NULL REFERENCES local(id),
                categoria_id BIGINT NOT NULL REFERENCES categoria(id),
                registrado_por BIGINT NOT NULL REFERENCES usuario(id),
                status VARCHAR(30) NOT NULL DEFAULT 'disponível'
            );

            CREATE TABLE IF NOT EXISTS reivindicacao (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                status_reivindicacao VARCHAR(30) NOT NULL DEFAULT 'pendente',
                data_solicitacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                item_id BIGINT NOT NULL REFERENCES item_perdido(id),
                aluno_id BIGINT NOT NULL REFERENCES aluno(aluno_id)
            );

            CREATE UNIQUE INDEX IF NOT EXISTS uq_reivindicacao_ativa
                ON reivindicacao (item_id, aluno_id)
                WHERE status_reivindicacao = 'pendente';
        `;
        await client.query(ddlQuery);

        // 2. Inserir Categorias e Locais
        console.log("Inserindo Categorias e Locais...");
        const insertEstaticos = `
            INSERT INTO categoria (nome) VALUES
                ('Chaves'), ('Garrafas'), ('Documentos'), 
                ('Eletronicos'), ('Bolsas'), ('Livros'), ('Outros')
            ON CONFLICT (nome) DO NOTHING;

            INSERT INTO local (nome_local, descricao) VALUES
                ('Bloco 1', 'Salas e corredores do Bloco 1'),
                ('Bloco 2', 'Salas e corredores do Bloco 2'),
                ('Biblioteca', 'Biblioteca do campus'),
                ('Restaurante Universitario', 'Area do restaurante universitario'),
                ('Quadra', 'Area esportiva'),
                ('Recepcao', 'Recepcao e portaria principal')
            ON CONFLICT (nome_local) DO NOTHING;
        `;
        await client.query(insertEstaticos);

        // 3. Inserir Admin e capturar ID
        console.log("Inserindo Usuários (Admin e Aluno)...");
        const resAdmin = await client.query(
            `INSERT INTO usuario (nome, email, senha, role) VALUES ($1, $2, $3, $4) RETURNING id;`,
            ['Administrador Sistema', 'admin@ufc.br', 'senha_hash_123', 'admin']
        );
        const adminId = resAdmin.rows[0].id;
        
        await client.query(
            `INSERT INTO administracao (id, siap) VALUES ($1, $2);`,
            [adminId, 123456789]
        );

        // 4. Inserir Aluno e capturar ID
        const resAluno = await client.query(
            `INSERT INTO usuario (nome, email, senha, role) VALUES ($1, $2, $3, $4) RETURNING id;`,
            ['João Estudante', 'joao@alu.ufc.br', 'senha_hash_123', 'aluno']
        );
        const alunoId = resAluno.rows[0].id;

        await client.query(
            `INSERT INTO aluno (aluno_id, matricula) VALUES ($1, $2);`,
            [alunoId, '2026100123']
        );

        // 5. Buscar IDs reais de Categoria e Local
        const resCat = await client.query(`SELECT id FROM categoria WHERE nome = 'Eletronicos'`);
        const idCatEletronicos = resCat.rows[0].id;

        const resLoc = await client.query(`SELECT id FROM local WHERE nome_local = 'Biblioteca'`);
        const idLocalBiblioteca = resLoc.rows[0].id;

        // 6. Registrar um Item Perdido (criado pelo Admin)
        console.log("Registrando item perdido e gerando reivindicação...");
        const resItem = await client.query(
            `INSERT INTO item_perdido (titulo, descricao, local_id, categoria_id, registrado_por) 
             VALUES ($1, $2, $3, $4, $5) RETURNING id;`,
            ['Calculadora Científica Casio', 'Calculadora preta encontrada na mesa 5.', idLocalBiblioteca, idCatEletronicos, adminId]
        );
        const itemId = resItem.rows[0].id;

        // 7. Criar a Reivindicação do Aluno
        await client.query(
            `INSERT INTO reivindicacao (item_id, aluno_id) VALUES ($1, $2);`,
            [itemId, alunoId]
        );

        // Confirma todas as operações
        await client.query('COMMIT');
        console.log("Carga de dados concluída com sucesso! Banco populado.");

    } catch (erro) {
        await client.query('ROLLBACK');
        console.error("Erro durante a carga. Transação revertida para proteger o banco de dados.", erro);
    } finally {
        await client.end();
        console.log("Conexão encerrada.");
    }
}

executarCarga();